"""add tile table

Revision ID: 2e348ead6839
Revises: ac2fcea77579
Create Date: 2026-04-06 18:57:11.679116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e348ead6839'
down_revision = 'ac2fcea77579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('hit_points', sa.Integer(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tile_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_tile_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tile_code'))
        batch_op.drop_index(batch_op.f('ix_tile_category'))

    op.drop_table('tile')
    # ### end Alembic commands ###
