"""Add plate_type to course and plate_index to course_tile

Revision ID: c032ba2bd368
Revises: d7b8e3e9291c
Create Date: 2026-04-07 11:54:34.196091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c032ba2bd368'
down_revision = 'd7b8e3e9291c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plate_type', sa.String(length=20), nullable=False))

    with op.batch_alter_table('course_tile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plate_index', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_tile', schema=None) as batch_op:
        batch_op.drop_column('plate_index')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('plate_type')

    # ### end Alembic commands ###
