"""add course and course_tile tables

Revision ID: d7b8e3e9291c
Revises: 2e348ead6839
Create Date: 2026-04-07 11:08:55.624188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b8e3e9291c'
down_revision = '2e348ead6839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('canvas_width', sa.Integer(), nullable=False),
    sa.Column('canvas_height', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_tile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('tile_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['tile_id'], ['tile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_tile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_tile_course_id'), ['course_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_tile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_tile_course_id'))

    op.drop_table('course_tile')
    op.drop_table('course')
    # ### end Alembic commands ###
